#define FIRMWARE_VERSION	0x0001
#define OTESTAMPER_ID		0xFD032A1C



//IMPORTANT: When debug is enabled, FRAME Interrupts are disabled
//#define DEBUG

#define F_CPU 8000000L

#define PIN_LED_PORT		PORTD
#define PIN_LED_PIN		PIND
#define PIN_LED_DDR		DDRD
#define PIN_LED_BIT		_BV(PD2)

#define PIN_FRAME_INT_PORT	PORTC
#define PIN_FRAME_INT_PIN	PINC
#define PIN_FRAME_INT_DDR	DDRC
#define PIN_FRAME_INT_BIT	_BV(PC3)

#define PIN_DEBUG_PORT		PIN_FRAME_INT_PORT
#define PIN_DEBUG_PIN		PIN_FRAME_INT_PIN
#define PIN_DEBUG_DDR		PIN_FRAME_INT_DDR
#define PIN_DEBUG_BIT		PIN_FRAME_INT_BIT

#define PIN_SPI_MISO_PORT	PORTB
#define PIN_SPI_MISO_PIN	PINB
#define PIN_SPI_MISO_DDR	DDRB
#define PIN_SPI_MISO_BIT	_BV(PB4)

#define PIN_SPI_MOSI_PORT	PORTB
#define PIN_SPI_MOSI_PIN	PINB
#define PIN_SPI_MOSI_DDR	DDRB
#define PIN_SPI_MOSI_BIT	_BV(PB3)

#define PIN_SPI_SCLK_PORT	PORTB
#define PIN_SPI_SCLK_PIN	PINB
#define PIN_SPI_SCLK_DDR	DDRB
#define PIN_SPI_SCLK_BIT	_BV(PB5)

#define PIN_SPI_CS_PORT		PORTB
#define PIN_SPI_CS_PIN		PINB
#define PIN_SPI_CS_DDR		DDRB
#define PIN_SPI_CS_BIT		_BV(PB2)

#define PIN_PPS_PORT		PORTD
#define PIN_PPS_PIN		PIND
#define PIN_PPS_DDR		DDRD
#define PIN_PPS_BIT		_BV(PD2)

#define PIN_XVS_PORT		PORTD
#define PIN_XVS_PIN		PIND
#define PIN_XVS_DDR		DDRD
#define PIN_XVS_BIT		_BV(PD3)

#define PIN_BUZZER_PORT		PORTD
#define PIN_BUZZER_PIN		PIND
#define PIN_BUZZER_DDR		DDRD
#define PIN_BUZZER_BIT		_BV(PD6)

#define PIN_FAN_PORT		PORTC
#define PIN_FAN_PIN		PINC
#define PIN_FAN_DDR		DDRC
#define PIN_FAN_BIT		_BV(PC5)

#define DEBUG_BAUD_RATE		9600
